<x-layouts.app title="Administration — Passerelle">
    <section class="dashboard-page container admin-page">
        <p class="eyebrow">ADMINISTRATION</p>
        <h1>Contrôler avant publication.</h1>
        <p class="muted">Vérifiez l’identité des entreprises et la qualité des offres avant de les rendre publiques.</p>
        @if(session('success'))<p class="success-message">{{ session('success') }}</p>@endif
        @error('offer')<p class="field-error">{{ $message }}</p>@enderror
        <section class="management-section"><div class="section-top"><div><p class="eyebrow">ENTREPRISES À VÉRIFIER</p><h2>{{ $companies->count() }} demande{{ $companies->count() > 1 ? 's' : '' }}</h2></div></div>
            @forelse($companies as $company)<article class="review-row"><div><p class="offer-meta">{{ $company->sector }} · {{ $company->city }}</p><h2>{{ $company->name }}</h2><p>{{ $company->description ?: 'Aucune présentation fournie.' }}</p><p class="review-contact">Responsable : {{ $company->owner->first_name }} {{ $company->owner->last_name }} · {{ $company->owner->email }}</p></div><div class="review-actions"><form method="post" action="{{ route('admin.companies.verify', $company) }}">@csrf @method('PATCH')<button class="button button-primary" type="submit">Vérifier</button></form><form method="post" action="{{ route('admin.companies.reject', $company) }}">@csrf @method('PATCH')<button class="button button-danger" type="submit">Refuser</button></form></div></article>@empty<div class="empty-offers"><strong>Aucune entreprise en attente.</strong><p>Les nouvelles demandes apparaîtront ici.</p></div>@endforelse
        </section>
        <section class="management-section"><div class="section-top"><div><p class="eyebrow">OFFRES À CONTRÔLER</p><h2>{{ $offers->count() }} offre{{ $offers->count() > 1 ? 's' : '' }}</h2></div></div>
            @forelse($offers as $offer)<article class="review-row"><div><p class="offer-meta">{{ $offer->company->name }} · {{ $offer->contractLabel() }} · {{ $offer->city }}</p><h2>{{ $offer->title }}</h2><p>{{ $offer->description }}</p></div><div class="review-actions"><form method="post" action="{{ route('admin.offers.publish', $offer) }}">@csrf @method('PATCH')<button class="button button-primary" type="submit">Publier</button></form><form method="post" action="{{ route('admin.offers.archive', $offer) }}">@csrf @method('PATCH')<button class="button button-danger" type="submit">Retirer</button></form></div></article>@empty<div class="empty-offers"><strong>Aucune offre en attente.</strong><p>Les offres soumises par les entreprises apparaîtront ici.</p></div>@endforelse
        </section>
        <section class="management-section"><div class="section-top"><div><p class="eyebrow">MESSAGES DE CONTACT</p><h2>{{ $messages->where('status', 'new')->count() }} nouveau{{ $messages->where('status', 'new')->count() > 1 ? 'x' : '' }}</h2></div></div>@forelse($messages as $message)<article class="review-row"><div><p class="offer-meta">{{ $message->status === 'new' ? 'NOUVEAU' : 'TRAITÉ' }} · {{ $message->created_at->translatedFormat('d M Y') }}</p><h2>{{ $message->subject }}</h2><p>{{ $message->message }}</p><p class="review-contact">{{ $message->name }} · <a href="mailto:{{ $message->email }}">{{ $message->email }}</a></p></div>@if($message->status === 'new')<div class="review-actions"><form method="post" action="{{ route('admin.messages.read', $message) }}">@csrf @method('PATCH')<button class="button button-secondary" type="submit">Marquer traité</button></form></div>@endif</article>@empty<div class="empty-offers"><strong>Aucun message de contact.</strong><p>Les demandes envoyées depuis le site apparaîtront ici.</p></div>@endforelse</section>
    </section>
</x-layouts.app>
