<x-layouts.app title="Mon espace étudiant — Passerelle">
    <section class="dashboard-page container">
        <p class="eyebrow">ESPACE ÉTUDIANT</p>
        <div class="dashboard-heading"><div><h1>Bonjour, {{ $user->first_name }}.</h1><p class="muted">Votre parcours, vos preuves, vos candidatures.</p></div><a class="button button-primary" href="{{ route('student.profile.edit') }}">{{ $profile ? 'Modifier mon profil' : 'Créer mon profil' }}</a></div>
        @if(session('success'))<p class="success-message">{{ session('success') }}</p>@endif
        <div class="student-summary"><article><p>PROFIL</p><strong>{{ $profile?->completion_percentage ?? 0 }} %</strong><span>complété</span></article><article><p>CANDIDATURES</p><strong>{{ $applications->count() }}</strong><span>envoyée{{ $applications->count() > 1 ? 's' : '' }}</span></article><article><p>PORTFOLIO</p><strong>{{ $profile?->projects()->count() ?? 0 }}</strong><span>projet{{ ($profile?->projects()->count() ?? 0) > 1 ? 's' : '' }}</span></article></div>
        <section class="management-section"><div class="section-top"><div><p class="eyebrow">SUIVI</p><h2>Vos candidatures</h2></div><a href="{{ route('offers.index') }}">Explorer les offres →</a></div>@forelse($applications as $application)<article class="offer-row"><div><p class="offer-meta">{{ $application->offer->company->name }} · {{ $application->offer->city }}</p><h2>{{ $application->offer->title }}</h2><p>Candidature envoyée le {{ $application->submitted_at->translatedFormat('d F Y') }} · <strong>{{ match($application->status) { 'submitted' => 'Envoyée', 'reviewed' => 'Consultée', 'shortlisted' => 'Présélectionnée', 'interview' => 'Entretien', 'accepted' => 'Acceptée', default => 'Non retenue' } }}</strong></p></div></article>@empty<div class="empty-offers"><strong>Aucune candidature pour le moment.</strong><p>Votre profil et vos projets vous aideront à présenter votre parcours avant de postuler.</p></div>@endforelse</section>
    </section>
</x-layouts.app>
